### ISSUE TITLE
Release version 0.3.0 on PyPi

### ISSUE THREAD

**Issue by tkw1536** [OpenMath/py-openmath#20]
With [#19](https://github.com/OpenMath/py-openmath/pull/19) merged, @defeo can you release version 0.3.0 on PyPi?

**Comment by defeo** [comment]
Done. Do you happen to know why README.rst is not automatically uploaded to PyPI: https://pypi.org/project/openmath/ ?

**Comment by tkw1536** [comment]
You need to add it under `long_description` in setup.py. See e.g. https://packaging.python.org/guides/making-a-pypi-friendly-readme/.
